### ISSUE TITLE
Ranger class is mentioned as a source of Figter's styles

### ISSUE THREAD

**Issue by kompoth** [canismarko/dungeon-sheets#88] opened 2020-12-02 17:59 UTC
Despite FighterFightingStyle defines `source = 'Fighter'`, in the output pdf file 'Defense' Fighter's style is sourced from Ranger's class. Not sure if the 'source' field was intended this way.

**Comment by canismarko** [comment] 2020-12-08 20:34
Not sure, but thanks for letting me know. I'll take a look when I have some free time.

**Comment by bw-mutley** [comment] 2022-01-03 18:33
It seens to be fixed. Tested with tex template and pdftk, could not reproduce it.

**Comment by canismarko** [comment] 2022-01-06 15:40
Sounds good. I'm going to close this. @kompoth: feel free to re-open if you have steps to reproduce this.

**Closed by canismarko** 2022-01-06 15:40 UTC
Labels: bug
